name: tekartik_serial_wss
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  node_interop: any

dev_dependencies:
  test: ">=0.12.0"
  grinder: any
  browser: ">=0.10.0"
  event_bus: any
  web_socket_channel: any
  tekartik_serial_wss_client:
    git: git://github.com/tekartik/serial_wss_client.dart
  dev_test: any
  tekartik_test_menu:
    git: git://github.com/tekartik/test_menu.dart
  tekartik_build_utils:
    git: git://github.com/tekartik/build_utils.dart
  tekartik_browser_utils:
    git: git://github.com/tekartik/browser_utils.dart

dependency_overrides:
#  tekartik_pub:
#    path: /media/ssd/devx/git/github.com/tekartik/pub.dart

transformers:
  - $dart2js
#  - node_interop